services:
  mysql:
    image: mysql:9.7.0
    container_name: email-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: email_service
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:4.3.1-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mysql_data:
  rabbitmq_data: